import Contact from "@/Components/Contact";
import MenuBar from "@/Components/MenuBar";

export const metadata = {
    title: 'Polako - Contato',
    description: 'Generated by create next app',
}

export default function contato () {
    return (
        <main className="h-screen bg-neutral-100">
            <MenuBar />
            <Contact />
        </main>
    )
}