import About from "@/Components/About";
import MenuBar from "@/Components/MenuBar";

export const metadata = {
    title: 'NINO - Sobre',
    description: 'Generated by create next app',
  }

export default function sobre () {
    return(
        <main className="h-screen bg-neutral-100">
            <MenuBar />
            <About />
        </main>
    )
}