import MenuBar from "@/Components/MenuBar";
import Servicos from "@/Components/Servicos";

export const metadata = {
    title: 'NINO - Serviços',
    description: 'Generated by create next app',
  }

export default function servicos () {
    return (
        <main className="h-screen bg-neutral-100">
            <MenuBar />
            <Servicos />
        </main>
    )
}