import { Akshar } from 'next/font/google'
import './globals.css'

const akshar = Akshar({ subsets: ['latin'] })

export const metadata = {
  title: 'Polako - Barbershop',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={akshar.className}>{children}</body>
    </html>
  )
}
